/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package co.edu.uniquindio.compiladores.modelo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 6;
  /** RegularExpression Id. */
  int NUMERO = 7;
  /** RegularExpression Id. */
  int RESTA = 8;
  /** RegularExpression Id. */
  int DIVISION = 9;
  /** RegularExpression Id. */
  int MULTIPLICACION = 10;
  /** RegularExpression Id. */
  int EXPONENTE = 11;
  /** RegularExpression Id. */
  int FINAL_LINEA = 12;
  /** RegularExpression Id. */
  int SENO = 13;
  /** RegularExpression Id. */
  int COSENO = 14;
  /** RegularExpression Id. */
  int TANGENTE = 15;
  /** RegularExpression Id. */
  int SECANTE = 16;
  /** RegularExpression Id. */
  int COSECANTE = 17;
  /** RegularExpression Id. */
  int COTAGENTE = 18;
  /** RegularExpression Id. */
  int PARENTESIS_IZQUIERDO = 19;
  /** RegularExpression Id. */
  int PARENTESIS_DERECHO = 20;
  /** RegularExpression Id. */
  int LLAVE_IZQUIERDA = 21;
  /** RegularExpression Id. */
  int LLAVE_DERECHA = 22;
  /** RegularExpression Id. */
  int CORCHETE_IZQUIERDO = 23;
  /** RegularExpression Id. */
  int CORCHETE_DERECHO = 24;
  /** RegularExpression Id. */
  int RAIZ = 25;
  /** RegularExpression Id. */
  int ENTERO = 26;
  /** RegularExpression Id. */
  int DOBLE = 27;
  /** RegularExpression Id. */
  int FLOTANTE = 28;
  /** RegularExpression Id. */
  int INTEGRAL = 29;
  /** RegularExpression Id. */
  int ASIGNACION = 30;
  /** RegularExpression Id. */
  int PUNTO = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"+\"",
    "<NUMERO>",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"^\"",
    "\";\"",
    "\"sen\"",
    "\"cos\"",
    "\"tan\"",
    "\"sec\"",
    "\"csc\"",
    "\"cot\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"rai\"",
    "\"ent\"",
    "\"dob\"",
    "\"flot\"",
    "\"int\"",
    "\"=\"",
    "\".\"",
  };

}
