/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package co.edu.uniquindio.compiladores.modelo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITOS = 6;
  /** RegularExpression Id. */
  int LETRA_MIN = 7;
  /** RegularExpression Id. */
  int LETRA_MAY = 8;
  /** RegularExpression Id. */
  int SUMA = 9;
  /** RegularExpression Id. */
  int RESTA = 10;
  /** RegularExpression Id. */
  int DIVISION = 11;
  /** RegularExpression Id. */
  int MULTIPLICACION = 12;
  /** RegularExpression Id. */
  int EXPONENTE = 13;
  /** RegularExpression Id. */
  int MODULO = 14;
  /** RegularExpression Id. */
  int SENO = 15;
  /** RegularExpression Id. */
  int COSENO = 16;
  /** RegularExpression Id. */
  int TANGENTE = 17;
  /** RegularExpression Id. */
  int SECANTE = 18;
  /** RegularExpression Id. */
  int COSECANTE = 19;
  /** RegularExpression Id. */
  int COTANGENTE = 20;
  /** RegularExpression Id. */
  int PARENTESIS_IZQUIERDO = 21;
  /** RegularExpression Id. */
  int PARENTESIS_DERECHO = 22;
  /** RegularExpression Id. */
  int LLAVE_IZQUIERDA = 23;
  /** RegularExpression Id. */
  int LLAVE_DERECHA = 24;
  /** RegularExpression Id. */
  int CORCHETE_IZQUIERDO = 25;
  /** RegularExpression Id. */
  int CORCHETE_DERECHO = 26;
  /** RegularExpression Id. */
  int RAIZ = 27;
  /** RegularExpression Id. */
  int ENTERO = 28;
  /** RegularExpression Id. */
  int DOBLE = 29;
  /** RegularExpression Id. */
  int FLOTANTE = 30;
  /** RegularExpression Id. */
  int INTEGRAL = 31;
  /** RegularExpression Id. */
  int DX_INTEGRAL = 32;
  /** RegularExpression Id. */
  int ASIGNACION = 33;
  /** RegularExpression Id. */
  int COMA = 34;
  /** RegularExpression Id. */
  int PUNTO = 35;
  /** RegularExpression Id. */
  int FINAL_LINEA = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<DIGITOS>",
    "<LETRA_MIN>",
    "<LETRA_MAY>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"^\"",
    "\"%\"",
    "\"Sen\"",
    "\"Cos\"",
    "\"Tan\"",
    "\"Sec\"",
    "\"Csc\"",
    "\"Cot\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"Rai\"",
    "\"Ent\"",
    "\"Dob\"",
    "\"Flot\"",
    "\"Intg\"",
    "\"Dx\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\";\"",
  };

}
